type: google.api.Service
config_version: 3

http:
  rules:
    # Blockchain APIs
    - selector: pactus.Blockchain.GetBlock
      get: "/v1/blockchain/block/height/{height}/verbosity/{verbosity}"

    - selector: pactus.Blockchain.GetBlockHash
      get: "/v1/blockchain/block_hash/{height}"

    - selector: pactus.Blockchain.GetBlockHeight
      get: "/v1/blockchain/block_height/{hash}"

    - selector: pactus.Blockchain.GetAccount
      get: "/v1/blockchain/account/address/{address}"

    - selector: pactus.Blockchain.GetAccountByNumber
      get: "/v1/blockchain/account/number/{number}"

    - selector: pactus.Blockchain.GetValidator
      get: "/v1/blockchain/validator/address/{address}"

    - selector: pactus.Blockchain.GetValidatorByNumber
      get: "/v1/blockchain/validator/{number}"

    - selector: pactus.Blockchain.GetBlockchainInfo
      get: "/v1/blockchain/info"

    # Transaction APIs
    - selector: pactus.Transaction.GetTransaction
      get: "/v1/transaction/id/{id}/verbosity/{verbosity}"

    - selector: pactus.Transaction.SendRawTransaction
      put: "/v1/transaction/send_raw_transaction/{data}"

    # Network APIs
    - selector: pactus.Network.GetNetworkInfo
      get: "/v1/network/info"

    - selector: pactus.Network.GetNodeInfo
      get: "/v1/network/node"

    # Wallet APIs
    - selector: pactus.Wallet.CreateWallet
      get: "/v1/wallet/create/name/{name}/mnemonic/{mnemonic}/language/{language}"

    - selector: pactus.Wallet.LoadWallet
      get: "/v1/wallet/load/name/{name}"

    - selector: pactus.Wallet.UnloadWallet
      get: "/v1/wallet/unload/name/{name}"

    - selector: pactus.Wallet.LockWallet
      get: "/v1/wallet/lock"

    - selector: pactus.Wallet.UnlockWallet
      get: "/v1/wallet/unlock/password/{password}/timeout/{timeout}"

