on: [push, pull_request]
name: Data race detection
jobs:
  data-race:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace sync.RWMutux with deadlock.RWMutux
      run: make replace_mutux

    - name: Test with data race detection
      run: make test_race
