name: Releaser
permissions:
  # https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions
  contents: write

on:
  push:
    tags: ["v*"]

jobs:
  ########################################
  build-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install zip

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Create release files
        run: bash ./.github/releasers/releaser_cli.sh

      - name: Calculate sha256sum
        run: sha256sum pactus-*.zip pactus-*tar.gz > checksum-cli.txt

      - name: Upload checksum artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-cli
          path: checksum-cli.txt

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pactus-*.zip
            pactus-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  build-gui-linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        name: [linux-amd64, linux-arm64]
        include:
          - name: linux-amd64
            runner: ubuntu-24.04
          - name: linux-arm64
            runner: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libcairo2-dev libglib2.0-dev libfuse2 pkg-config dpkg dpkg-dev

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Create release files
        run: bash ./.github/releasers/releaser_gui_linux.sh

      - name: Calculate sha256sum
        run: sha256sum pactus-gui*.tar.gz pactus-gui*.tar.gz > checksum-${{ matrix.name }}.txt

      - name: Upload checksum artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-${{ matrix.name }}
          path: checksum-${{ matrix.name }}.txt

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pactus-gui*.tar.gz
            pactus-gui*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  build-gui-macos:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        name: [macos-amd64, macos-arm64]
        include:
          - name: macos-amd64
            runner: macos-13
            lib_home: /usr/local
          - name: macos-arm64
            runner: macos-14
            lib_home: /opt/homebrew

    env:
      LIB_HOME: ${{ matrix.lib_home }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install gtk+3 librsvg create-dmg coreutils gdk-pixbuf glib-networking

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Create release files
        run: bash ./.github/releasers/releaser_gui_macos.sh

      - name: Calculate sha256sum
        run: sha256sum pactus-*.dmg pactus-*.tar.gz > checksum-${{ matrix.name }}.txt

      - name: Upload checksum artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-${{ matrix.name }}
          path: checksum-${{ matrix.name }}.txt

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pactus-*.dmg
            pactus-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  build-gui-windows:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        name: [windows-amd64, windows-arm64]
        include:
          - name: windows-amd64
            runner: windows-latest
          - name: windows-arm64
            runner: windows-11-arm

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git
            make
            p7zip
            glib2-devel
            mingw-w64-x86_64-go
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config

      - name: Create release files
        run: bash ./.github/releasers/releaser_gui_windows.sh

      # ########################
      # Signing installer: start
      - name: upload-unsigned-artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'pactus-installer'
          path: pactus-*installer.exe
          if-no-files-found: error

      - name: sign
        uses: signpath/github-action-submit-signing-request@v1.1
        env:
          # select release-signing policy for main and release branches
          SIGNPATH_SIGNING_POLICY_SLUG: |
            ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/'))
              && 'release-signing'
              || 'test-signing' }}
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ vars.SIGNPATH_ORGANIZATION_ID }}'
          project-slug: 'Pactus'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{steps.upload-unsigned-artifact.outputs.artifact-id}}'
          wait-for-completion: true
          output-artifact-directory: 'pactus-signed'

      - name: upload-signed-artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'pactus-signed'
          path: 'pactus-signed'
          if-no-files-found: error
      # Signing installer: end
      # ######################

      - name: Calculate sha256sum
        run: sha256sum pactus-*.zip ./pactus-signed/pactus-*installer.exe > checksum-${{ matrix.name }}.txt

      - name: Upload checksum artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-${{ matrix.name }}
          path: checksum-${{ matrix.name }}.txt

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pactus-*.zip
            ./pactus-signed/pactus-*installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  checksums:
    needs:
      [
        build-cli,
        build-gui-linux,
        build-gui-macos,
        build-gui-windows,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Download checksum artifacts
        uses: actions/download-artifact@v4
        with:
          path: checksums

      - name: Combine checksums
        run: |
          cat checksums/*/*.txt > SHA256SUMS
          cat SHA256SUMS

      - name: Upload SHA256SUMS as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sha256sums
          path: SHA256SUMS

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  cosign:
    needs: [checksums]
    runs-on: ubuntu-latest
    steps:
      - name: Download SHA256SUMS artifact
        uses: actions/download-artifact@v4
        with:
          name: sha256sums

      - uses: sigstore/cosign-installer@v3

      - name: Sign Checksum
        run: cosign sign-blob --yes --key env://COSIGN_PRIVATE_KEY SHA256SUMS > SHA256SUMS.sig
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: SHA256SUMS.sig

  ########################################
  downloader:
    needs: [cosign]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Downloader file
        run: |
          VERSION="$(echo `git -C . describe --abbrev=0 --tags` | sed 's/^.//')" # "v1.2.3" -> "1.2.3"
          echo ${VERSION}
          sed -i "s/__VERSION__/${VERSION}/g" .github/releasers/pactus_downloader.sh

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: .github/releasers/pactus_downloader.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
