name: Semantic PR
permissions:
  pull-requests: read

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which scopes are allowed (newline-delimited).
          scopes: |
            github
            linter
            deps
            makefile
            release
            releaser
            packager
            other
            daemon
            cmd
            firewall
            gtk
            shell
            wallet-cmd
            committee
            config
            consensus
            crypto
            docs
            execution
            genesis
            network
            node
            sandbox
            scripts
            sortition
            state
            store
            sync
            main
            txpool
            types
            util
            version
            wallet
            www
            grpc
            proto
            jsonrpc
            http
            html
            zeromq
            windows
            linux
            macos
          # Configure that a scope must always be provided.
          requireScope: true
          # The subject should not start with an uppercase character and should not end with a period.
          subjectPattern: ^(?![A-Z]).+[^.]$
          subjectPatternError: |
            The subject "{subject}" cannot start with an uppercase character or end with a period.
