name: Test macOS Signing

on:
  pull_request:

jobs:
  test-gui-macos:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        name: [macos-amd64, macos-arm64]
        include:
          - name: macos-amd64
            runner: macos-15-intel
            lib_home: /usr/local
          - name: macos-arm64
            runner: macos-15
            lib_home: /opt/homebrew

    env:
      LIB_HOME: ${{ matrix.lib_home }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required for git describe

      - name: Install Dependencies
        run: brew install gtk+3 librsvg create-dmg coreutils gdk-pixbuf glib-networking pkg-config

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.0"

      - name: Import macOS Certificates
        if: ${{ secrets.MACOS_CERTIFICATE != '' }}
        uses: apple-actions/import-codesign-certs@v6
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}

      - name: Create release files
        run: bash ./.github/releasers/releaser_gui_macos.sh
        env:
          MACOS_CERT_IDENTITY: ${{ secrets.MACOS_CERT_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: pactus-gui-test-${{ matrix.name }}
          path: |
            pactus-*.dmg
            pactus-*.tar.gz
